### ISSUE TITLE
README文档一处小问题

### ISSUE THREAD

**Issue by arslantu** [HCLonely/hexo-steam-games#1]
[手动获取游戏库数据](https://github.com/HCLonely/hexo-steam-games#%E6%89%8B%E5%8A%A8%E8%8E%B7%E5%8F%96%E6%B8%B8%E6%88%8F%E5%BA%93%E6%95%B0%E6%8D%AE)这一部分，地址`https://steamcommunity.com/id/{steamId}/games?tab={tab}`中应该把`id`改为`profiles`。

**Comment by HCLonely** [comment]
感谢，已修改
